version: '3'
services:
  broker-rabbitmq:
    image: "rabbitmq:3.7.14-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
  db-postgres:
    image: "postgres:11.2"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
  migration:
    build: .
    environment:
      - APP_ENV=${APP_ENV}
    command: flask db upgrade
    depends_on:
      - db-postgres
  api:
    build: .
    ports:
     - "5000:5000"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
      - migration
  api-worker:
    build: .
    command: celery worker --workdir=. -A tasks.celery --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
      - migration
  api-beat:
    build: .
    command: celery beat -A tasks.celery --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
      - migration